import type { Schema } from 'hast-util-sanitize';

const allowedTagNames: Schema['tagNames'] = [
  'a',
  'blockquote',
  'br',
  'code',
  'del',
  'em',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'hr',
  'img',
  'li',
  'ol',
  'picture',
  'p',
  'pre',
  'strong',
  'u',
  'ul',
  'video',
  'audio',
  'source',
  'table',
  'thead',
  'tbody',
  'tfoot',
  'tr',
  'th',
  'td',
  'svg',
  'g',
  'path',
  'rect',
  'circle',
  'ellipse',
  'line',
  'polyline',
  'polygon',
  'text',
  'tspan',
  'defs',
  'clipPath',
  'mask',
  'pattern',
  'marker',
  'linearGradient',
  'radialGradient',
  'stop',
  'symbol',
  'use',
  'title',
  'desc',
  'style',
];

const allowedProtocols: string[] = ['http', 'https', 'mailto'];

export const markdownSanitizeSchema: Schema = {
  tagNames: allowedTagNames,
  attributes: {
    a: [
      'href',
      ['target', '_blank', '_self'],
      ['rel', 'noopener', 'noreferrer', 'nofollow'],
    ],
    code: [
      ['className', /^language-[\w-]+$/],
    ],
    img: ['src', 'alt', 'title', 'width', 'height', 'loading'],
    ol: [
      ['start', /^-?\d+$/],
      ['type', '1', 'a', 'A', 'i', 'I'],
      'reversed',
    ],
    li: [
      ['value', /^-?\d+$/],
    ],
    video: ['src', 'controls', 'preload', 'width', 'height', 'poster'],
    audio: ['src', 'controls', 'preload'],
    source: ['src', 'type'],
    th: ['align'],
    td: ['align'],
    svg: [
      'className',
      'id',
      'role',
      'aria-label',
      'aria-hidden',
      'focusable',
      'width',
      'height',
      'viewBox',
      'preserveAspectRatio',
      'xmlns',
      'xmlnsXlink',
      'style',
    ],
    g: [
      'className',
      'id',
      'transform',
      'fill',
      'fillOpacity',
      'stroke',
      'strokeWidth',
      'strokeDasharray',
      'strokeLinecap',
      'strokeLinejoin',
      'strokeMiterlimit',
      'strokeOpacity',
      'opacity',
      'style',
      'clipPath',
    ],
    path: [
      'className',
      'id',
      'd',
      'fill',
      'fillOpacity',
      'stroke',
      'strokeWidth',
      'strokeDasharray',
      'strokeLinecap',
      'strokeLinejoin',
      'strokeMiterlimit',
      'strokeOpacity',
      'opacity',
      'style',
      'markerEnd',
      'markerStart',
      'markerMid',
      'transform',
    ],
    rect: [
      'className',
      'id',
      'x',
      'y',
      'width',
      'height',
      'rx',
      'ry',
      'fill',
      'fillOpacity',
      'stroke',
      'strokeWidth',
      'strokeOpacity',
      'opacity',
      'style',
      'transform',
    ],
    circle: [
      'className',
      'id',
      'cx',
      'cy',
      'r',
      'fill',
      'fillOpacity',
      'stroke',
      'strokeWidth',
      'strokeOpacity',
      'opacity',
      'style',
      'transform',
    ],
    ellipse: [
      'className',
      'id',
      'cx',
      'cy',
      'rx',
      'ry',
      'fill',
      'fillOpacity',
      'stroke',
      'strokeWidth',
      'strokeOpacity',
      'opacity',
      'style',
      'transform',
    ],
    line: [
      'className',
      'id',
      'x1',
      'y1',
      'x2',
      'y2',
      'stroke',
      'strokeWidth',
      'strokeDasharray',
      'strokeOpacity',
      'opacity',
      'style',
      'transform',
    ],
    polyline: [
      'className',
      'id',
      'points',
      'fill',
      'fillOpacity',
      'stroke',
      'strokeWidth',
      'strokeDasharray',
      'strokeOpacity',
      'opacity',
      'style',
      'transform',
    ],
    polygon: [
      'className',
      'id',
      'points',
      'fill',
      'fillOpacity',
      'stroke',
      'strokeWidth',
      'strokeDasharray',
      'strokeOpacity',
      'opacity',
      'style',
      'transform',
    ],
    text: [
      'className',
      'id',
      'x',
      'y',
      'dx',
      'dy',
      'textAnchor',
      'dominantBaseline',
      'alignmentBaseline',
      'fontFamily',
      'fontSize',
      'fontWeight',
      'fill',
      'fillOpacity',
      'opacity',
      'style',
      'transform',
    ],
    tspan: [
      'className',
      'id',
      'x',
      'y',
      'dx',
      'dy',
      'textAnchor',
      'dominantBaseline',
      'alignmentBaseline',
      'fontFamily',
      'fontSize',
      'fontWeight',
      'fill',
      'fillOpacity',
      'opacity',
      'style',
      'transform',
    ],
    defs: ['id'],
    clipPath: ['id', 'clipPathUnits'],
    mask: ['id', 'maskUnits', 'maskContentUnits'],
    pattern: ['id', 'x', 'y', 'width', 'height', 'patternUnits', 'patternContentUnits'],
    marker: ['id', 'markerWidth', 'markerHeight', 'refX', 'refY', 'orient', 'markerUnits', 'viewBox'],
    linearGradient: ['id', 'x1', 'y1', 'x2', 'y2', 'gradientUnits', 'gradientTransform'],
    radialGradient: ['id', 'cx', 'cy', 'r', 'fx', 'fy', 'gradientUnits', 'gradientTransform'],
    stop: ['offset', 'stopColor', 'stopOpacity'],
    symbol: ['id', 'viewBox', 'preserveAspectRatio'],
    use: ['href', 'xlinkHref', 'x', 'y', 'width', 'height'],
    title: ['id'],
    desc: ['id'],
    style: ['type'],
  },
  protocols: {
    href: [...allowedProtocols],
    src: ['http', 'https', 'agyn'],
    xlinkHref: [...allowedProtocols],
  },
};
